#%RAML 1.0 DocumentationItem

collection:
  usage: type for collections
  description: Description <<resourcePath | !singularize>>
  get:
    responses:
      200:
      404:
  post:
    responses:
      200:
      404:
